T-Labs/exchange-sdk

- TLabs.ExchangeSdk/Currencies/Currency.cs
**added new fields to currency**
_public string Website { get; set; }
public string WhitePaper { get; set; }
public string About { get; set; }
public string IssuingTime { get; set; }
public string IssuingPrice { get; set; }
public string TotalSupply { get; set; }
public string NetworkConfirmations { get; set; }
public byte[] LogoImage { get; set; }_
> added new fields to currency

- TLabs.ExchangeSdk/Bwp/ClientBwp.cs
- TLabs.ExchangeSdk/Bwp/TraderSetting.cs
added TraderSetting model and methods to the bwp client. updated version
> added TraderSetting model and methods to the bwp client. updated version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
added GetChatFileMetadata to ClientP2P class to get chat file metadata by its ID.
> added GetChatFileMetadata to ClientP2P 

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Order.cs
- TLabs.ExchangeSdk/P2P/OrderUserInfo.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Change Deal, Order, OrderUserInfo

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Order.cs
- TLabs.ExchangeSdk/P2P/OrderUserInfo.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-OrderUserInfo, added IsKYCPassed, RequesterCanOpenDeal fields
for working order settings
> Change OrderUserInfo

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-CancelOrder method, added orderUserId parameter
-UpdateDealPaymentStatus method, renaming to UpdateDealPaymentStatus and added  userId parameter
-CancelDeal method, added userId parameter
-OpenDealAppeal, new method added
> Change ClientP2P, update app version

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-Deal, added DateAppealed
-Deal, renaming USDTRate to CryptoAmountInUsdt
> Change P2P/Deal, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/ClientUsers.cs
- TLabs.ExchangeSdk/Users/CustomClaim.cs
-ClientUsers, added GetClaims, CreateOrUpdateClaims methods. -Updated app version
> Change ClientUsers, update app

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Update app version

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealAppeal.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-Deal, added DealAppeals, removed AppealAdminId
-DealAppeal, new class added
> Change p2p Deal, add DealAppeal

- TLabs.ExchangeSdk/P2P/Chats/ChatMessageCreateDto.cs
- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealAppeal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealAppealCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-ChatMessageCreateDto, removed [Required] for UserId field. -DealAppealCreateDto, added [Required] for DealId,Cause  fields. -Deal, new status added AppealedAfterFinish
-DealAppeal, new type added AppealType
-ClientP2P, code style fixed
> Change ChatMessageCreateDto, Deal, DealAppeal, DealAppealCreateDto

- TLabs.ExchangeSdk/P2P/Chats/FileMetadataDto.cs
- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-FileMetadataDto, added new class that passes file metadata -Client P2P, the GetChatFileMetadata method has been changed, the userId parameter has been added and the response type has been changed.
> Add P2P.Chats FileMetadataDto, change ClientP2P

- TLabs.ExchangeSdk/P2P/Chats/ChatFileMetadataDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-FileMetadataDto, renamed to ChatFileMetadataDto,
added fields Id, FileSize
> Change FileMetadataDto, update app version

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealStatusRules.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
-Deal, added UserVerificationName, deleted
-DealStatus, deleted Appealed, AppealedAfterFinish -DealStatusRules, added a new class representing state transition rules 
> Change P2P Deal, add DealStatusRules, update app version

- TLabs.ExchangeSdk/P2P/Chats/ChatMessage.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ChatMessage, added Deal field
> Change P2P ChatMessage, update app version

- TLabs.ExchangeSdk/P2P/Chats/ChatUsersInfo.cs
- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Deal, removed UserVerificationName.
- ChatUsersInfo, added ChatUsersInfo a new class representing information about chat participants
> Change Deal, add ChatUsersInfo, update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- GetChatUsersInfo, added a new controller method to get information about chat participants
> Add  ClientP2P GetChatUsersInfo, update app version

- TLabs.ExchangeSdk/P2P/Deals/DealAppeal.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- DealAppeal, added AppealType field
> Change P2P DealAppeal, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/UserClaims.cs
- UserClaims, added new BanOnP2P claim
> Change UserClaims, update app version

- TLabs.ExchangeSdk/P2P/Order.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Order, added FilledOrderAmount
> Change P2P Order

- TLabs.ExchangeSdk/P2P/Users/UserTradingLimitsDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- UserLimits, added a new class responsible for checking the possibility of opening deals and orders
> Add P2P UserLimits , update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Users/UserDealLimitsDto.cs
- TLabs.ExchangeSdk/P2P/Users/UserOrderLimitsDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Fix using and namespace, update app version

- TLabs.ExchangeSdk/P2P/Users/UserDealLimitsDto.cs
- TLabs.ExchangeSdk/P2P/Users/UserOrderLimitsDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Change UserOrderLimitsDto, UserDealLimitsDto

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/WebApp/ClientWebapp.cs
- ClientWebapp, changed route in the SendP2PDealNotification method
> Change ClientWebapp, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/WebApp/ClientWebapp.cs
- TLabs.ExchangeSdk/WebApp/P2PNotification.cs
- ClientWebapp, changed route
- P2PNotification, added P2PChat target, added constructors.
> Change ClientWebapp, P2PNotification, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Verification/VerificationUser.cs
- VerificationUser, added UserVerificationStage class responsible for the user verification stage
> Change VerificationUser, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Verification/TypeIdentityCard.cs
- TLabs.ExchangeSdk/Verification/TypeProofOfAddress.cs
- TLabs.ExchangeSdk/Verification/VerificationCard.cs
- TLabs.ExchangeSdk/Verification/VerificationChangeNotifications.cs
- TLabs.ExchangeSdk/Verification/VerificationUser.cs
- VerificationChangeNotifications
-  VerificationCard
- TypeProofOfAddress
-  TypeIdentityCard
> Add new files

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Verification/VerificationUser.cs
- VerificationUser, renamed UserVideo to UserAuthenticationVideo
> Change VerificationUser

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Verification/VerificationUpdateDto.cs
- VerificationUpdateDto, added a class to update user verification status,
> Add VerificationUpdateDto, update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Deals/DealCancellationDispute.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientP2P, added GetDealDispute, UpdateDealDisputeStatus
- DealCancellationDispute, added DealCancellationDispute class representing the resolution of a dispute after the cancellation of a deal
> Change ClientP2P, add DealCancellationDispute

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Deals/DealCancellationDispute.cs
- TLabs.ExchangeSdk/P2P/Deals/DealDisputeCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- DealDisputeCreateDto, added DealDisputeCreateDto class representing the reason for canceling the deal
> Add DealDisputeCreateDto

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/WebApp/P2PNotification.cs
- ClientP2P, added GetDealDisputes
- P2PNotificationTarget, added new target P2PSellerDispute
> Change ClientP2P, P2PNotificationTarget, update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Deals/DealDispute.cs
- TLabs.ExchangeSdk/P2P/Users/UserInfoDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- DealDispute, renamed DealCancellationDispute to DealDispute
- UserInfoDto, added RatingBasedOnDealsAfterDisputes field
> Change DealDispute, UserInfoDto, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/ClientUsers.cs
- TLabs.ExchangeSdk/Users/UserClaims.cs
- ClientUsers, added GetUserClaimValue and SetUserClaim methods
- UserClaims, added TempBanOnP2PExpiryDate
> Change ClientUsers, UserClaims, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/ClientUsers.cs
- TLabs.ExchangeSdk/Users/UserFinancesSetting.cs
- ClientUsers, added GetUserSettings, SetUserSettings, GetCommissionConversionSettings, SetTradeCommissionConversionSetting methods
- UserFinancesSetting, added new class.
> Change ClientUsers, add UserFinancesSetting

- TLabs.ExchangeSdk/P2P/Deals/DealDisputeCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- DealDisputeCreateDto, removed "Required" for CreatorUserId
> Change DealDisputeCreateDto, update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealCancelDispute.cs
- TLabs.ExchangeSdk/P2P/Deals/DealCancelDisputeCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/WebApp/P2PNotification.cs
Renamed all Deal Cancel Dispute related files
> Rename P2P DealDispute to DealCancelDispute

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
This reverts commit 5fb5efe3117a5d957b2d6f2b71c4516c3c9a841f, reversing changes made to 312c9dbd2dfdafbd496ba0b86a6f1b7e9beab7ba.
#	TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Revert "Merge pull request #136 from T-Labs/IgorDevR_P2P"

- TLabs.ExchangeSdk/Currencies/CurrencyListings/CurrencyListing.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrencyListing, added new properties
> Change CurrencyListing, update app version

- TLabs.ExchangeSdk/News/ClientNews.cs
- TLabs.ExchangeSdk/News/Dtos/NewsDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientNews, renamed methods, fixed parameters, fixed route paths.
- NewsDto, added DateCreated property
> Change ClientNews, NewsDto, update app version

- TLabs.ExchangeSdk/Currencies/CurrencyListings/ClientCurrencyListings.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientCurrencyListings, deleted DeleteComment method.
> Change ClientCurrencyListings

- TLabs.ExchangeSdk/News/ClientNews.cs
- TLabs.ExchangeSdk/News/NewsItemViewModel.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Created, fixed route
- NewsItemViewModel, renamed Created to DateCreated.
> Change ClientNews, NewsItemViewModel

- TLabs.ExchangeSdk/News/ClientNews.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Change ClientNews, update app version

- TLabs.ExchangeSdk/Currencies/CurrencyListings/ClientCurrencyListings.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientCurrencyListings, fixed Comment and CommentCount methods.
> Change ClientCurrencyListings, update app version

- TLabs.ExchangeSdk/Currencies/CurrencyListings/ClientCurrencyListings.cs
- TLabs.ExchangeSdk/News/ClientNews.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientNews, added GetImageFileContentResult, and parameter to
GetNewsViewModels, GetNewsById.
- ClientCurrencyListings, renamed methods.
> Change ClientNews, ClientCurrencyListings.

- TLabs.ExchangeSdk/News/ClientNews.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientNews, fixed route in UpdateCommentLike.
> Change , update app version

- TLabs.ExchangeSdk/Farming/ActionTask.cs
- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/Farming/Dtos/ActionTaskDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/RegistrationDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/TenantDataDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/UploadImageDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/UserReferralsDto.cs
- TLabs.ExchangeSdk/Farming/Image.cs
- TLabs.ExchangeSdk/Farming/Referral.cs
- TLabs.ExchangeSdk/Farming/Reward.cs
- TLabs.ExchangeSdk/Farming/Tenant.cs
- TLabs.ExchangeSdk/Farming/Transaction.cs
- TLabs.ExchangeSdk/Farming/User.cs
- TLabs.ExchangeSdk/Farming/UserTask.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Add Farming models and ClientFarming

- TLabs.ExchangeSdk/Farming/Commons/HeadersData.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Add HeadersData, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Fix return value in ClaimDailyReward

- TLabs.ExchangeSdk/ServiceCollectionExtensions.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ServiceCollectionExtensions, added ClientFarming
> Change ServiceCollectionExtensions

- TLabs.ExchangeSdk/Farming/Dtos/TenantDataDto.cs
- TLabs.ExchangeSdk/Farming/Tenant.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Change TenantDataDto, Tenant, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/Farming/TenantsCache.cs
- TLabs.ExchangeSdk/ServiceCollectionExtensions.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarming, added ReloadTenants.
- TenantsCache, added GetTenantById.
> Change ClientFarming, TenantsCache, update app version

- TLabs.ExchangeSdk/Farming/Dtos/RegistrationDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- RegistrationDto, removed fields.
> Change RegistrationDto, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarming, removed FromBody.
> Change ClientFarming, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/Farming/ClientFarmingAdmin.cs
- TLabs.ExchangeSdk/Farming/Dtos/RewardCreateDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/TenantCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarmingAdmin, changed parameters type in Reward and Tenant.
- , Added TenantCreateDto, RewardCreateDto.
> Change ClientFarmingAdmin, add dtos, update app version

- TLabs.ExchangeSdk/Farming/ClientFarmingAdmin.cs
- TLabs.ExchangeSdk/Farming/Dtos/TenantSettingsCreateDto.cs
- TLabs.ExchangeSdk/Farming/Tenant.cs
- TLabs.ExchangeSdk/Farming/TenantSettings.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarmingAdmin, added TenantSettings requests.
- TenantSettings, added class for setting up tenant.
- TenantSettingsCreateDto, added class for creating TenantSettings.
> Change ClientFarmingAdmin, update app version

- TLabs.ExchangeSdk/Farming/ActionTask.cs
- TLabs.ExchangeSdk/Farming/Dtos/ActionTaskDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ActionTask, renamed Priority to Ordering, added AvailableDayNumber.
- ActionTaskDto, renamed Priority to Ordering, added AvailableDayNumber.
> Change ActionTask, ActionTaskDto, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/Farming/Dtos/UploadImageDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarming, added GetRewardByType.
> Change ClientFarming, UploadImageDto, update app version

- TLabs.ExchangeSdk/Farming/ClientFarming.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- ClientFarming, change the return type of ClaimRewardForMiniGame and GetRewardByType.
> Change ClientFarming

- TLabs.ExchangeSdk/Farming/Dtos/TenantCreateDto.cs
- TLabs.ExchangeSdk/Farming/Dtos/TenantDataDto.cs
- TLabs.ExchangeSdk/Farming/Tenant.cs
- TLabs.ExchangeSdk/Farming/Transaction.cs
- TLabs.ExchangeSdk/Farming/User.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Tenant, added TokenDecimalPlaces.
- Transaction, added added Transactions.
- User, added RecipientUser.
> Change Tenant, Transaction, User, update app version

- TLabs.ExchangeSdk/Farming/UserTask.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- UserTask, fixed DateClaimed.
> Change UserTask, update app version

- TLabs.ExchangeSdk/Currencies/CurrencyListings/ClientCurrencyListings.cs
- TLabs.ExchangeSdk/Currencies/CurrencyListings/CurrencyListing.cs
- TLabs.ExchangeSdk/Currencies/CurrencyListings/CurrencyListingCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrencyListing, renamed link fields, added TokenDecimalPlaces, HeaderImageId, removed NewsDescriptionHtml.
- Update app version.
> Change CurrencyListing, add CurrencyListingCreateDto

- TLabs.ExchangeSdk/Currencies/CurrencyListings/CurrencyListingCreateDto.cs
- TLabs.ExchangeSdk/News/UploadImage.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- UploadImage, fixed Extension name.
> Change UploadImage, update app version

- TLabs.ExchangeSdk/Currencies/CurrencyListings/CurrencyListingCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrencyListingCreateDto, added MarketPageDisplayOrder.
> Change CurrencyListingCreateDto, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Trading/ClientMarketdata.cs
- TLabs.ExchangeSdk/Trading/CurrencyPairData.cs
- TLabs.ExchangeSdk/Trading/OhlcData.cs
- TLabs.ExchangeSdk/Trading/ResponseOHLC.cs
- ClientMarketdata, added new marketdata methods.
Added CurrencyPairData, OhlcData, ResponseOHLC models.
> Change ClientMarketdata

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Trading/ClientMarketdata.cs
- ClientMarketdata, fixed route CurrencyPairsData.
> Change ClientMarketdata, update app version

- TLabs.ExchangeSdk/Farming/ClientFarmingAdmin.cs
- TLabs.ExchangeSdk/Farming/Transaction.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
method CreateTransaction in ClientFarmingAdmin
> add new field to TransactionType,

- TLabs.ExchangeSdk/Farming/Dtos/TenantDataDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TenantDataDto, removed BotToken.
> Change TenantDataDto, update app version

- TLabs.ExchangeSdk/Farming/Dtos/TenantDataDto.cs
- TLabs.ExchangeSdk/Farming/Tenant.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Tenant, added AnalyticsScriptId.
- TenantDataDto, added AnalyticsScriptId.
> Change Tenant, TenantDataDto, update app version

- TLabs.ExchangeSdk/RabbitMq/EmailTemplateSender.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- EmailTemplateSender, added SendGoogle2FAEmailCode.
> Change EmailTemplateSender, update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/ClientUsers.cs
- ClientUsers, added methods for google 2fa.
> Change ClientUsers, update app version

- TLabs.ExchangeSdk/P2P/ClientP2P.cs
- TLabs.ExchangeSdk/P2P/PaymentMethodDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- PaymentMethodDto, added IsActive field.
- ClientP2P, added UpdatePaymentMethod.
> Change PaymentMethodDto, ClientP2P, update app version

- TLabs.ExchangeSdk/Currencies/CurrenciesCache.cs
- TLabs.ExchangeSdk/Currencies/P2PExchangeCurrency.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrenciesCache, added methods and parameters for P2PExchangeCurrencies.
> Change CurrenciesCache. Add P2PExchangeCurrency

- TLabs.ExchangeSdk/Currencies/CurrenciesCache.cs
- TLabs.ExchangeSdk/Depository/ClientDepository.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Renamed parameters, added check for loading P2PExchangeCurrencies.
> Change CurrenciesCache

- TLabs.ExchangeSdk/P2P/Deals/Deal.cs
- TLabs.ExchangeSdk/P2P/Deals/DealCreateDto.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
> Change P2P Deal, DealCreateDto, update app version

- TLabs.ExchangeSdk/Currencies/CurrenciesCache.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrenciesCache, fixed parameter name in LoadData.
> Change CurrenciesCache, update app version

- TLabs.ExchangeSdk/P2P/CurrencyPairTradingVolume.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- CurrencyPairTradingVolume, added TotalExchangeAmount and
TotalPaymentAmount fields.
> Change CurrencyPairTradingVolume

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/UserClaims.cs
- UserClaims, added P2PEmailNotification
> Change UserClaims. Update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Withdrawals/ClientWithdrawals.cs
- TLabs.ExchangeSdk/Withdrawals/WithdrawalSettingsKeys.cs
- ClientWithdrawals, added GetParameter and UpdateParameter.
> Change ClientWithdrawals, add WithdrawalSettingsKeys

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Withdrawals/ClientWithdrawals.cs
- ClientWithdrawals, renamed GetParameterValue.
> Change ClientWithdrawals. Update app version

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/UserSettingsKeys.cs
- TLabs.ExchangeSdk/Withdrawals/WithdrawalSettingsKeys.cs
- Removed WithdrawalSettingsKeys.
> Rename UserConstants to UserSettingsKeys.

- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- TLabs.ExchangeSdk/Users/UserSettingsKeys.cs
> Change UserSettingsKeys. Update app version

- TLabs.ExchangeSdk/Currencies/CurrenciesCache.cs
- TLabs.ExchangeSdk/TLabs.ExchangeSdk.csproj
- Combined 2 parameters into 1 when loading p2p currencies.
> Change CurrenciesCache. Update app version
